server:
  port: 50010
  
spring:
  rabbitmq:
    host: o2c.ovh
    port: 5672
    username: master-pay
    password: master123
  data:
    mongodb:
      database: mp_transactions
      host: localhost
      
#logging:
#  level:
#    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
   
management:
  endpoints:
    web:
      exposure:
        include: "*"    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   

amqp:
  transactions:
    exchange:
      updated:
        transaction: updated_transaction
    queue:
      init-transaction:
        created:
           response: init_transaction_created_response_queue
      transaction:
        completed:
          request: transaction_completed_response_queue
      payment:
        completed:
          response: payment_completed_transaction_response_queue
          
  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events          

  authorizations:
    exchange:
      completed:
        authorization: completed_authorization
    queue:
      authorization:
        completed:
          response: authorization_completed_response_queue

  captures:
    exchange:
      completed:
        capture: completed_capture
    queue:
      capture:
        completed:
          response: capture_completed_response_queue          

  refunds:
    exchange:
      completed:
        refund: completed_refund
    queue:
      refunde:
        completed:
          response: refund_completed_response_queue              

environment:
  nifi-url: http://localhost:60056
  callback-url: ${environment.nifi-url}/completeTransactionCallback
  
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:50068/validateClient
      
---
spring:
  profiles: integration
  data:
    mongodb:
      database: mp_transactions
      host: localhost
      port: 27018
